### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by Renbago** [jithin8mathew/Depth-estimation-using-Depth-Camera-D435i-for-YOLOv5-detected-objects#1]
Hello sir im gettint those error's
Traceback (most recent call last):
  File "C:/Depth-estimation-using-Depth-Camera-D435i-for-YOLOv5-detected-objects-main/realDetect.py", line 12, in <module>
    from models.experimental import attempt_load
  File "C:\Depth-estimation-using-Depth-Camera-D435i-for-YOLOv5-detected-objects-main\models\experimental.py", line 7, in <module>
    from models.common import Conv, DWConv
  File "C:\Depth-estimation-using-Depth-Camera-D435i-for-YOLOv5-detected-objects-main\models\common.py", line 13, in <module>
    from utils.datasets import letterbox
ModuleNotFoundError: No module named 'utils.datasets'

from utils.google_utils import attempt_download

Process finished with exit code 1

**Comment by edenespin** [comment]
@Renbago  how did you fix this?

**Comment by jithin8mathew** [comment]
@edenespin, the error is likely to do with the YOLOv5 version. Make sure to use the correction version of YOLOv5 (YOLOv5 (v3), I don't remember the commit number) to solve this issue. I will work on implementing this project in YOLOv8 soon and will also take a look at the current issue.
